services:
  - type: web
    name: meu-menu-fit
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
